### ISSUE TITLE
pages and menuItems

### ISSUE THREAD

**Issue by nightillusions** [wdj-ac/wondercms#1]
There are a few problems:
- ~~when a menuItem is updated and the slug is different than before => the old page "falls into nirvana".~~
- the Pages need a unique identifier, which makes it easier to update. 
- ~~if there are more new menuItems generated at once, the system creates pages with same slug.~~

**Comment by robiso** [comment]
To add to the list, this shows up in the error log when trying to change the visibility of an element
 - PHP Warning:  Attempt to modify property of non-object in index.php on line 117 - line 117 is `case 5: $db->{$args[0]}->{$args[1]}->{$args[2]}->{$args[3]} = $args[4]; break;`

Error log when trying to add a new menu item:
 - PHP Warning:  get_object_vars() expects parameter 1 to be object, array given in index.php on line 184 - line 184 is `$menuCount = count(get_object_vars(wCMS::get('config', $fieldname)));`
 - PHP Warning:  Attempt to assign property of non-object in index.php on line 185 - line 185 is `$db = wCMS::db();$db->config->{$fieldname}->{$menuCount} = new stdClass; wCMS::save($db);`
 - PHP Warning:  Attempt to modify property of non-object in index.php on line 117 - line 117 is `case 5: $db->{$args[0]}->{$args[1]}->{$args[2]}->{$args[3]} = $args[4]; break;`

I wasn't able to generate new menu items or change their visibility on a fresh installation. I'll do a re-test later in case I missed anything.

// also replied here https://github.com/robiso/wondercms/issues/21 about the function url

**Comment by nightillusions** [comment]
> if there are more new menuItems generated at once, the system creates pages with same slug.

fixed in commit 9b206105af54f33a8c49d7dde2d69c19c0295aa7

----------------
@robiso 
> error log when trying to change the visibility && Error log when trying to add a new menu item: 

Please try the last quick fix. There was a problem on initial database creation, which caused faulty menuItems object => 9b206105af54f33a8c49d7dde2d69c19c0295aa7

**Comment by robiso** [comment]
Confirming that nothing gets in the error log anymore. Adding and changing visibility still seems like it lags a couple of page refreshes/actions to take effect. Example - after clicking hide or show, you have to refresh the page again for this to take effect.

If you're curious how this works in our environment, you check it out at https://www.wondercms.com/w202/ with your latest patches. Hope to give you more feedback soon.

**Comment by nightillusions** [comment]
Fixed visibility lags
