### ISSUE TITLE
JS Problem: sporadically the action abort (delete, hide/show)

### ISSUE THREAD

**Issue by nightillusions** [wdj-ac/wondercms#2]
Sometimes the actions to hide/show or delete a menut item aborts.

Possible reason: _redirect() fires to early?

**Comment by robiso** [comment]
Did this happen on 404 pages or any other specific cases? If it halts, what happens after a refresh, does the action still get carried out as mentioned here? https://github.com/wdj-ac/wondercms/issues/1#issuecomment-294589047

**Comment by nightillusions** [comment]
Fixed with commit 8da96ca61b11b54f5736dce1441ed6ce424de793
