### ISSUE TITLE
Cannot create additional menus or show/hide on 404 page +fix

### ISSUE THREAD

**Issue by robiso** [wdj-ac/wondercms#3]
This happens when the logged in user is on a non-existent page (hasn't created any content for that page).
A 404 header is returned, so the code halts or waits for the next refresh.

This happens because of an error in the WonderCMS logic, which **returns a header 404 if the user is logged in**, and not the other way around, which is a bug in WonderCMS.

To make this all go away, change this condition
`if (wCMS::$loggedIn && ! wCMS::$currentPageExists) header("HTTP/1.0 404 Not Found");`
to
`if (! wCMS::$loggedIn && ! wCMS::$currentPageExists) header("HTTP/1.0 404 Not Found");`
This makes sure to return 404 only when the user is not logged in, which is also better for SEO, so search engines are able to recognize 404 pages.

We'll probably wait and fix these bugs either in your repo and merge them later or add them manually to our repo. And publish everything in 2.0.3 when we're done...

@wdj-ac loving your work :+1:

**Comment by nightillusions** [comment]
@robiso Thank you! If I have enough time, I will continue to work on it. At the moment, there are unfortunately also other construction sites. Maybe tomorrow I will find some time for the rest of the problems :)
