### ISSUE TITLE
Pages that aren't in the menu in version 2.0.6 don't get transferred when updating to 2.1.0

### ISSUE THREAD

**Issue by robiso** [wdj-ac/wondercms#8]
There's an issue where someone updates WonderCMS under the following scenario:
 - user has pages that are not in the menu in version 2.0.6
 - when updating to 2.1.0 (which we're working on), those pages are gone - the pages that weren't in the menu in users version 2.0.6 were not transferred to version 2.1.0
- other pages (those that were in the menu) were transferred successfully

**Comment by robiso** [comment]
Would a change in your update script that would foreach through pages instead of menu items work?

**Comment by nightillusions** [comment]
Yes of course! It could be something like this (UNTESTED):
```
foreach ($olddb->pages as $pages) {
                $newMenu->{$i} = new stdClass;
                $newMenu->{$i}->name = $pages->title;
                $newMenu->{$i}->slug = wCMS::_slugify($pages->title);
                $newMenu->{$i}->visibility = "show";
                $i++;
            }
```
Be aware, that all pages are visible in the menu after this update procedure. So the admin has to hide the unwanted menu items after updating wonderCMS.

**Comment by robiso** [comment]
Completely understood, it makes sense they're visible and thank you. Thanks to your help, they'll easily hide those pages :grin:. Putting this up for a test and reporting back.

Just to check, unsetting doesn't need changing, correct? `unset($olddb->config->menuItems);$olddb->config->menuItems = $newMenu;$olddb->config->dbVersion = '2.1.0';wCMS::save($olddb);`

**Comment by nightillusions** [comment]
Yes, the `unset` and the other parts are essential to perform the new menu update

**Comment by robiso** [comment]
Was just checking if anything needed changing there, thanks :+1:.
Coming back with some short feedback about the update functionality: seems to be working perfectly.

**Comment by robiso** [comment]
Attaching the latest index.php below with added JSON_UNESCAPED_UNICODE to prevent converting of some characters ({"a":"\u00e1"} {"a":"á"}

[index.php.zip](https://github.com/wdj-ac/wondercms/files/981223/index.php.zip)
(without extended slugifier, without the search engines part).

This seems to be ready for production (2.1.0). Before we push it out and, I'm testing out additional scenarios and trying to make some of the code shorter.

I have a question regarding this:
(line 229 - is encoding and decoding necessary here?
`if ($menu) {$menuItems = json_decode(json_encode(wCMS::get('config', 'menuItems')), TRUE);`
(and line 230 - is it also necessary here?)
`$db->config->menuItems = json_decode(json_encode($newMenu))`

**Comment by robiso** [comment]
Another update to the index.php, this version has multiple encoding fixes (some of them were also ghost pages with characters like &scaron instead of š.

This was fix by using html_entities_decode after calling json_decode. This now correctly retains all characters as they where, without any loss.

Will take this for a couple of more spins and tests, I will also send it to turboblack since he's an awesome tester.

@wdj-ac I'd like to take this chance to thank you once again. Rest assure you'll be properly publicly credited and once we get some more donations you and Robbie and first on the list to get rewarded.

Latest index.php // all special characters retaining solved + also perfectly retained without any loss (characters were converted to &scaron or /u190)
[index.php.zip](https://github.com/wdj-ac/wondercms/files/981641/index.php.zip)

What do you think @wdj-ac?
// closing this issue but hoping to continue this discussion
