### ISSUE TITLE
Pages with spaces 404 after updating (but exist in database)

### ISSUE THREAD

**Issue by robiso** [wdj-ac/wondercms#9]
A very specific bug where pages that have spaces in them _get transferred_ with the update, but do not work (404).

Example of a specific menu item after updating. **This item exists in the database after updating, but visiting this page at _website.com/wondercms-up-button_ returns a 404**. (where as _website.com/wondercms up button_ page worked in the old version).

```
    "menuItems": {
            "3": {
                "name": "Wondercms Up Button",
                "slug": "wondercms-up-button",
                "visibility": "show"
            }
        }
    },
    "pages": {
        "wondercms up button": {
            "title": "Wondercms Up Button",
            "keywords": "test",
            "description": "test",
            "content": "test"
        },
```

All the pages that did not have spaces in the page name/slug like the example above - worked without any issues.

I believe this bug is present in all the versions we worked on. Here is the latest index.php that I mentioned a day ago: [index.php.zip](https://github.com/wdj-ac/wondercms/files/987463/index.php.zip) to be worked on.

EDIT: This happens because the pages aren't slugified as shown below.
Is there any way we can slugify the pages during the update process?
```
    "pages": {
        "wondercms up button": { // slugify this param
            "title": "Wondercms Up Button",
            "keywords": "test",
            "description": "test",
            "content": "test"
        },
```

**Comment by nightillusions** [comment]
~~This seems to be a new problem of your last edits in the zipped index.php. Look at my last commit of this branch => No Problem with unslugified pages.~~

[EDIT] Okay sorry, now I see. It´s during the update process. If we want to catch this problem, we have to build all pages again. I will try to fix this.

**Comment by nightillusions** [comment]
@robiso Try this:

```
if ($olddb->config->dbVersion < '2.1.0') {
            $newMenu = new stdClass();
            $newPages = new stdClass();
            $i = 0;
            foreach ($olddb->pages as $page) {
                $slug = wCMS::_slugify($page->title);
                $newMenu->{$i} = new stdClass;
                $newMenu->{$i}->name = $page->title;
                $newMenu->{$i}->slug = $slug;
                $newMenu->{$i}->visibility = "show";
                $newPages->{$slug} = new stdClass;
                $newPages->{$slug}->title = $page->title;
                $newPages->{$slug}->keywords = $page->keywords;
                $newPages->{$slug}->description = $page->description;
                $newPages->{$slug}->content = $page->content;
                $i++;
            }
            unset($olddb->config->menuItems);
            unset($olddb->pages);

            $olddb->config->menuItems = $newMenu;
            $olddb->pages = $newPages;
            $olddb->config->dbVersion = '2.1.0';
            wCMS::save($olddb);
        }
```

**Comment by robiso** [comment]
Brilliant work @wdj-ac.

Modified your code to be a bit shorter, we now slugify the page from the page name itself, not from the title.

I believe we're one last step from the final picture, I'll try to modify the commented part below when I get home ($newMenu->{$i}->slug should be the page name instead of the title. I think this should be the case because the titles are usually custom and can be different from the actual page name.

```
if ($olddb->config->dbVersion < '2.1.0') {
	$newMenu = new stdClass();
	$newPages = new stdClass();
	$i = 0;
	
	foreach ($olddb->pages as $pageName => $val) {
		$slugPage = wCMS::_slugify($pageName);
		$newPages->$slugPage = $val;
	}
	
	foreach ($olddb->pages as $page) {
		$slug = wCMS::_slugify($page->title);
		$newMenu->{$i} = new stdClass;
		$newMenu->{$i}->name = $page->title;
		$newMenu->{$i}->slug = $slug; // value should be page name, not title
		$newMenu->{$i}->visibility = "show";
		$i++;
	}

	unset($olddb->config->menuItems);
	unset($olddb->pages);

	$olddb->config->menuItems = $newMenu;
	$olddb->pages = $newPages;
	$olddb->config->dbVersion = '2.1.0';
	wCMS::save($olddb);
}
```

**Comment by robiso** [comment]
Thanks to Luka Mrovlje for the
 - code clean up + making the code shorter
 - slug is now taken from the slugified page name instead of page title

Shortified code with the minor slug fix
```
if ($olddb->config->dbVersion < '2.1.0') {
	$newMenu = new stdClass();
	$newPages = new stdClass();
	$i = 0;
	foreach ($olddb->pages as $pageName => $page) {
		$slugPage = wCMS::_slugify($pageName);
		$newPages->$slugPage = $page;
		$newMenu->{$i} = new stdClass;
		$newMenu->{$i}->name = $page->title;
		$newMenu->{$i}->slug = $slugPage;
		$newMenu->{$i}->visibility = "show";
		$i++;
	}
	unset($olddb->config->menuItems);
	unset($olddb->pages);
	$olddb->config->menuItems = $newMenu;
	$olddb->pages = $newPages;
	$olddb->config->dbVersion = '2.1.0';
	wCMS::save($olddb);
}
```

Latest index.php: [index.php.zip](https://github.com/wdj-ac/wondercms/files/1005930/index.php.zip)
Will give this a couple of tests and run-arounds. It can then be pushed as 2.1.0 in the following days.

This issue can be closed as you've already solved the topic problem earlier.
